version: "3"

services:
  api:
    build: .
    image: pigeon
    container_name: pigeon
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./users.json:/app/users.json
    devices:
      - /dev/ttyUSB0:/dev/mobile
